name: linting-and-code-formatting

on: 
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout IMAS-Validator sources
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # until saxonche is available in 3.13
          # https://saxonica.plan.io/issues/6561
          python-version: "<3.13"

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install the code linting and formatting tools
        run: pip install --upgrade .[linting]

      - name: Check formatting of code with black
        run: black --check imas_validator

      - name: Check linting with flake8
        run: flake8 imas_validator

      - name: Check mypy
        run: mypy imas_validator

      - name: Check imports with isort
        run: isort --check-only imas_validator